INSERT INTO productos(nombre, precio, create_at) VALUES ('Panasonic', 800, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Sony', 700, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Apple', 1000, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Sony Notebook', 212, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Hewlett', 123, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Bianchi', 324, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Nike', 234, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Adidas', 2534, NOW())
INSERT INTO productos(nombre, precio, create_at) VALUES ('Reebok', 34534, NOW())